# Generated by Django 3.0.8 on 2020-09-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20200915_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
