# Generated by Django 3.0.8 on 2020-09-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20200915_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(default='nn', upload_to=''),
            preserve_default=False,
        ),
    ]
