# Generated by Django 3.0.8 on 2020-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_staffs_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='staffs/bulkupload/')),
            ],
        ),
    ]
